// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: execute_command.proto

package gRPC

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CmdExecutorClient is the client API for CmdExecutor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CmdExecutorClient interface {
	ExecuteCmd(ctx context.Context, in *ExecuteMsg, opts ...grpc.CallOption) (*ExecuteRes, error)
}

type cmdExecutorClient struct {
	cc grpc.ClientConnInterface
}

func NewCmdExecutorClient(cc grpc.ClientConnInterface) CmdExecutorClient {
	return &cmdExecutorClient{cc}
}

func (c *cmdExecutorClient) ExecuteCmd(ctx context.Context, in *ExecuteMsg, opts ...grpc.CallOption) (*ExecuteRes, error) {
	out := new(ExecuteRes)
	err := c.cc.Invoke(ctx, "/core.CmdExecutor/ExecuteCmd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CmdExecutorServer is the server API for CmdExecutor service.
// All implementations must embed UnimplementedCmdExecutorServer
// for forward compatibility
type CmdExecutorServer interface {
	ExecuteCmd(context.Context, *ExecuteMsg) (*ExecuteRes, error)
	mustEmbedUnimplementedCmdExecutorServer()
}

// UnimplementedCmdExecutorServer must be embedded to have forward compatible implementations.
type UnimplementedCmdExecutorServer struct {
}

func (UnimplementedCmdExecutorServer) ExecuteCmd(context.Context, *ExecuteMsg) (*ExecuteRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCmd not implemented")
}
func (UnimplementedCmdExecutorServer) mustEmbedUnimplementedCmdExecutorServer() {}

// UnsafeCmdExecutorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CmdExecutorServer will
// result in compilation errors.
type UnsafeCmdExecutorServer interface {
	mustEmbedUnimplementedCmdExecutorServer()
}

func RegisterCmdExecutorServer(s grpc.ServiceRegistrar, srv CmdExecutorServer) {
	s.RegisterService(&CmdExecutor_ServiceDesc, srv)
}

func _CmdExecutor_ExecuteCmd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdExecutorServer).ExecuteCmd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.CmdExecutor/ExecuteCmd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdExecutorServer).ExecuteCmd(ctx, req.(*ExecuteMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// CmdExecutor_ServiceDesc is the grpc.ServiceDesc for CmdExecutor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CmdExecutor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.CmdExecutor",
	HandlerType: (*CmdExecutorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteCmd",
			Handler:    _CmdExecutor_ExecuteCmd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "execute_command.proto",
}
