// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/app": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "application"
                ],
                "summary": "Get all key-value pairs",
                "operationId": "get-all",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.GetAllResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "application"
                ],
                "summary": "Set value to key",
                "operationId": "set-value-to-key",
                "parameters": [
                    {
                        "description": "Key and value to set",
                        "name": "key",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/utils.KeyVal"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.SetResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "application"
                ],
                "summary": "Delete all key-value pairs",
                "operationId": "delete-all",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.DelAllResponse"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "application"
                ],
                "summary": "Append value to key",
                "operationId": "append-value-to-key",
                "parameters": [
                    {
                        "description": "Key and value to append",
                        "name": "key",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/utils.KeyVal"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.AppendResponse"
                        }
                    }
                }
            }
        },
        "/app/{key}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "application"
                ],
                "summary": "Get value by key",
                "operationId": "get-value-by-key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Key to get",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.GetResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "application"
                ],
                "summary": "Delete value by key",
                "operationId": "delete-value-by-key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Key to delete",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.DeleteResponse"
                        }
                    }
                }
            }
        },
        "/app/{key}/strlen": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "application"
                ],
                "summary": "Get value string length by key",
                "operationId": "get-value-string-length-by-key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Key to get",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.StrlenResponse"
                        }
                    }
                }
            }
        },
        "/cluster/ping": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cluster"
                ],
                "summary": "Ping cluster",
                "operationId": "ping-cluster",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.PingResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.AppendResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/utils.KeyVal"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.DelAllResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/utils.KeyVal"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.DeleteResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/utils.KeyVal"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.GetAllResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/utils.KeyVal"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.GetResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/utils.KeyVal"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.PingResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.SetResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/utils.KeyVal"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.StrlenResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/utils.KeyVal"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "utils.KeyVal": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Web Client API",
	Description:      "This is the API documentation for the web client of the application.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
